# Generated by Django 6.0.1 on 2026-02-23 14:46

import django.core.validators
import django.db.models.deletion
import submission.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_course_code_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('changes_required', 'Changes Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('file', models.FileField(upload_to=submission.models.submission_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('plagiarism_score', models.FloatField(blank=True, help_text='Automated plagiarism detection score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_score', models.FloatField(blank=True, help_text='Automated AI content detection score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True)),
                ('feedback_file', models.FileField(blank=True, help_text='Optional feedback file', null=True, upload_to='submission_feedback/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('changes_required', 'Changes Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submission.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submission__status_832d62_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['course', 'status'], name='submission__course__787c02_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'course'], name='submission__student_2dfbc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'course', 'version')},
        ),
        migrations.AddIndex(
            model_name='submissionreview',
            index=models.Index(fields=['submission', '-created_at'], name='submission__submiss_a4de47_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionreview',
            index=models.Index(fields=['lecturer'], name='submission__lecture_e47b34_idx'),
        ),
    ]
