# Generated by Django 6.0.1 on 2026-03-12 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_code_secret'),
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['is_draft'], name='submission__is_draf_abab72_idx'),
        ),
    ]
