# Generated by Django 6.0.1 on 2026-02-12 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User ID from User Service who created this school', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='school.school'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='school.school'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_code', 'id'], name='school_scho_school__aa0e27_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['status'], name='school_scho_status_e28b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['city', 'country'], name='school_scho_city_e197bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schooladmin',
            unique_together={('school', 'user_id')},
        ),
    ]
