# Generated by Django 6.0.1 on 2026-02-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code_secret',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
